version: '3.9'

services:
  bdd:
    image: mariadb:latest
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: nimda
      MARIADB_DATABASE: roger
      MARIADB_USER: user
      MARIADB_PASSWORD: resu

